#!/bin/bash

# Customed Commands
titles=(
  "显示根目录"
  "显示Home目录"
  "重启服务器"
)
commands=(
  "ls /"
  "ls ~"
  "sudo reboot"
)

# Customed menu
MENU_TITLE="NMENU"
HEIGHT=0
WIDTH=0

# Confirm dialog
display_confirm_dialog() {
  # $1 command name
  if dialog --backtitle $MENU_TITLE --yesno "Please confirm again?" $HEIGHT $WIDTH
  then
    clear
    echo $1
    eval $1
    exit
  else
     clear
     echo "Cancel the command."
     exit
  fi
}

# Run command
while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle $MENU_TITLE \
    --clear \
    --cancel-label "Exit" \
    --menu "Please select:" $HEIGHT $WIDTH 0 \
    "1" "${titles[0]}" \
    "2" "${titles[1]}" \
    "3" "${titles[2]}" \
     2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    1) # DIALOG_CANCEL
      clear
      echo "Program terminated."
      exit
      ;;
    255) # DIALOG_ESC
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac

  display_confirm_dialog "${commands[$selection - 1]}"
done
